### ISSUE TITLE
riscv64 support

### ISSUE THREAD

**Issue by olof-nord** [cronokirby/saferith#48] opened 2022-04-10 11:28 UTC
Hello @cronokirby!

I wanted to run the ProtonMail [proton-bridge](https://github.com/ProtonMail/proton-bridge) software on my riscv64 machine.

As riscv64 is in its early days, this lead me to building proton-bridge from source which for most things golang actually works fine since ca 2020 when it got supported.

But, then this library comes by and when building gives me the below errors.

Now, looking at the repo and its file names, I assume a file `arith_riscv64.s` is needed (?) - I own riscv64 hardware (a HiFive Unmatched) and am happy to dig into this. How can I contribute? What would be the best path forward here?

```shell
➜  proton-bridge git:(master) make build-nogui                
go build -tags='' -ldflags '-X github.com/ProtonMail/proton-bridge/internal/constants.Version=2.1.2+git -X github.com/ProtonMail/proton-bridge/internal/constants.Revision=3b07121f08 -X github.com/ProtonMail/proton-bridge/internal/constants.BuildTime=2022-04-10T11:17:16+0000' -o proton-bridge cmd/Desktop-Bridge/main.go
# github.com/cronokirby/saferith
vendor/github.com/cronokirby/saferith/arith_decl.go:10:6: missing function body
vendor/github.com/cronokirby/saferith/arith_decl.go:11:6: missing function body
vendor/github.com/cronokirby/saferith/arith_decl.go:12:6: missing function body
vendor/github.com/cronokirby/saferith/arith_decl.go:13:6: missing function body
vendor/github.com/cronokirby/saferith/arith_decl.go:14:6: missing function body
vendor/github.com/cronokirby/saferith/arith_decl.go:15:6: missing function body
vendor/github.com/cronokirby/saferith/arith_decl.go:16:6: missing function body
make: *** [Makefile:69: build-nogui] Error 2
➜  proton-bridge git:(master) 
```

**Comment by cronokirby** [comment] 2022-04-10 15:18
Right, so the issue is that this code relies on assembly, like Go's `math/big` does, but we haven't gotten around to adding all of the assembly for various architectures yet.

Thankfully, we haven't written our own assembly, but rather used the assembly written inside of Go's `math/big`. So, if you look at the source code for `math/big` https://cs.opensource.google/go/go/+/master:src/math/big/, you'll see a bunch of `arith_X` files. In theory, just copying these over would make this library work on all packages (you know, I should've thought of doing that already a year ago).

Now, looking at the assembly files for RISCV, they just jump to the pure go routines, which should be slower. One further bit of work would be to try and write the assembly for those routines, but I don't think we really have to worry about that just yet.

Anyways, I should be able to quickly add the missing files, and put a new release in; if you could try building and running the project on your RISCV setup that would be great as well :)

**Comment by cronokirby** [comment] 2022-04-10 15:50
Alrighty, I've published version v0.33.0 of this package, providing support for different assembly architectures. It would be great if could try and build this package and have the tests pass.

**Comment by olof-nord** [comment] 2022-04-10 18:46
wow, thank you for replying so soon, and for providing a solution!

As for testing:

Running the tests as per readme:

```shell
➜  saferith git:(main) go test -bench=.
goos: linux
goarch: riscv64
pkg: github.com/cronokirby/saferith
BenchmarkLimbMask-4                 	13402308	        93.76 ns/op
BenchmarkAddBig-4                   	  523360	      2265 ns/op
BenchmarkModAddBig-4                	 1292887	       969.8 ns/op
BenchmarkLargeModAddBig-4           	  449287	      2633 ns/op
BenchmarkMulBig-4                   	   21580	     55962 ns/op
BenchmarkModMulBig-4                	 1345645	       888.4 ns/op
BenchmarkLargeModMulBig-4           	   19758	     59565 ns/op
BenchmarkModBig-4                   	   85617	     13992 ns/op
BenchmarkLargeModBig-4              	    9649	    112409 ns/op
BenchmarkModInverseBig-4            	  381486	      3214 ns/op
BenchmarkLargeModInverseBig-4       	   63690	     19139 ns/op
BenchmarkExpBig-4                   	    2462	    481022 ns/op
BenchmarkLargeExpBig-4              	       3	 444804750 ns/op
BenchmarkSetBytesBig-4              	  362220	      2891 ns/op
BenchmarkModSqrt3Mod4Big-4          	    1054	   1143179 ns/op
BenchmarkAddNat-4                   	  519256	      2363 ns/op
BenchmarkModAddNat-4                	  678657	      1681 ns/op
BenchmarkLargeModAddNat-4           	  140967	      8107 ns/op
BenchmarkModNegNat-4                	  987981	      1216 ns/op
BenchmarkLargeModNegNat-4           	  187940	      6285 ns/op
BenchmarkMulNat-4                   	    5845	    180446 ns/op
BenchmarkModMulNat-4                	  239851	      4943 ns/op
BenchmarkLargeModMulNat-4           	    2943	    411806 ns/op
BenchmarkLargeModMulNatEven-4       	    2868	    408639 ns/op
BenchmarkModNat-4                   	    7208	    150103 ns/op
BenchmarkLargeModNat-4              	    4696	    264983 ns/op
BenchmarkModInverseNat-4            	  118808	     10233 ns/op
BenchmarkLargeModInverseNat-4       	     190	   6232950 ns/op
BenchmarkModInverseEvenNat-4        	     188	   6358705 ns/op
BenchmarkLargeModInverseEvenNat-4   	     176	   6784355 ns/op
BenchmarkExpNat-4                   	     856	   1390676 ns/op
BenchmarkLargeExpNat-4              	       2	 586085794 ns/op
BenchmarkLargeExpNatEven-4          	       1	1769223628 ns/op
BenchmarkSetBytesNat-4              	  218690	      5201 ns/op
BenchmarkMontgomeryMul-4            	    5442	    215865 ns/op
BenchmarkModSqrt3Mod4Nat-4          	     865	   1450455 ns/op
BenchmarkModSqrt1Mod4Nat-4          	     252	   4571398 ns/op
BenchmarkDivNat-4                   	    7780	    155059 ns/op
BenchmarkLargeDivNat-4              	    4825	    252909 ns/op
PASS
ok  	github.com/cronokirby/saferith	74.861s
➜  saferith git:(main)
```

Adjusting the version information for proton-bridge allows me to build it as well, really nice!

I did try out running the proton-bridge tests on riscv64 too after the successful build, but there seems to be at least one unsuccessful test. I dont have enough knowledge about the proton-bridge project and its internals to go further, but ill mention it to them and suggest them to pull in version v0.33.0.

**Comment by olof-nord** [comment] 2022-04-10 18:47
Oh, and in case it matters, here some specific os info from the riscv system.

```
➜  proton-bridge git:(master) ✗ go version && uname -a
go version go1.17 linux/riscv64
Linux c-3po 5.13.0-1017-generic #19-Ubuntu SMP Tue Mar 15 16:43:13 UTC 2022 riscv64 riscv64 riscv64 GNU/Linux
➜  proton-bridge git:(master) ✗
```

Really appreciate your assistance!

**Comment by cronokirby** [comment] 2022-04-10 18:49
Thanks for running the tests! Closing this for now then.

**Closed by cronokirby** 2022-04-10 18:49 UTC
